export const TRANSLATIONS = {
  en: {
    nav: { collections: 'COLLECTIONS', perfumes: 'PERFUMES', clothing: 'CLOTHING', search: 'Search...', admin: 'Admin Panel', store: 'Storefront' },
    hero: { subtitle: 'NEW COLLECTION 2024', title: 'Essence of Elegance', cta: 'Shop Now' },
    store: { title: 'Curated Selection', description: 'Discover our hand-picked collection of artisanal fragrances and bespoke apparel.', all: 'All', perfume: 'Perfume', clothing: 'Clothing', addToBag: 'Add to Bag', noProducts: 'No products found', adjustSearch: 'Try adjusting your search or filters.' },
    product: { back: 'Back to collection', inStock: 'In stock', lowStock: 'Only {count} left', outOfStock: 'Out of stock', notes: 'Fragrance notes', materials: 'Materials', material: 'Material', color: 'Color', scentFamily: 'Scent family', topNotes: 'Top notes', heartNotes: 'Heart notes', baseNotes: 'Base notes', volume: 'Volume', size: 'Size', delivery: 'Delivery', defaultNote: 'Signature blend', defaultMaterial: 'Premium finish', defaultColor: 'Seasonal color', defaultScentFamily: 'Signature scent', defaultVolume: '50 ml', defaultSize: 'One size', defaultDelivery: 'Delivery in 2-4 business days' },
    cart: { title: 'Shopping Bag', empty: 'Your bag is empty', itemCount: '{count} items in your bag', startShopping: 'Start Shopping', continueShopping: 'Continue Shopping', clear: 'Clear Bag', each: 'each', stockLimit: 'Max stock reached', subtotal: 'Subtotal', shipping: 'Shipping', shippingNote: 'Calculated at checkout', total: 'Total', checkout: 'Checkout Now', hideCheckout: 'Hide Checkout' },
    checkout: { title: 'Order Confirmation', description: 'Review the order, add delivery details, then send it to the seller on WhatsApp.', orderSummary: 'Order summary', paymentInstructions: 'Payment instructions', whatsapp: 'Send order on WhatsApp', bank: 'Bank information', bankName: 'Bank', accountHolder: 'Account holder', rib: 'RIB', iban: 'IBAN', note: 'Use the bank details above for transfer payments. After payment, send the transfer receipt by WhatsApp.', customerDetails: 'Customer details:', form: { title: 'Delivery details', name: 'Full name', phone: 'Phone number', city: 'City', address: 'Address', notes: 'Delivery notes (optional)', required: 'Name, phone, city, and address are required before sending.' }, messageGreeting: 'Hello, I would like to place this order:', messageDelivery: 'Please confirm availability and delivery details.' },
    admin: { title: 'Inventory Management', description: 'Manage your product catalog, stock levels, and inventory value.', addBtn: 'Add New Product', search: 'Search products...', lowStock: 'Low stock', stats: { products: 'Products', units: 'Units in stock', value: 'Inventory value', lowStock: 'Low stock' }, seller: { title: 'Seller Settings', description: 'Update the WhatsApp and bank information customers see during checkout.', whatsapp: 'WhatsApp', bankName: 'Bank name', accountHolder: 'Account holder', rib: 'RIB', iban: 'IBAN', save: 'Save Seller Info' }, table: { product: 'Product', category: 'Category', price: 'Price', stock: 'Stock', actions: 'Actions', units: 'units' }, modal: { addTitle: 'Add New Product', editTitle: 'Edit Product', name: 'Product Name', desc: 'Description', price: 'Price (MAD)', stock: 'Stock', category: 'Category', image: 'Image URL', preview: 'Image preview', previewHelp: 'The product image will appear here.', imageFallback: 'Image could not load, so the fallback image is shown.', volume: 'Volume', scentFamily: 'Scent Family', topNotes: 'Top Notes', heartNotes: 'Heart Notes', baseNotes: 'Base Notes', size: 'Size', color: 'Color', material: 'Material', delivery: 'Delivery', commaSeparated: 'Separate values with commas', save: 'Save Changes', create: 'Create Product' }, deleteConfirm: 'Are you sure you want to delete this product?' },
    footer: { desc: 'Crafting timeless elegance through artisanal fragrances and bespoke fashion. Our mission is to bring luxury and quality to your everyday life.', shop: 'Shop', support: 'Support', rights: '© 2024 Luxe & Loom Boutique. All rights reserved.', privacy: 'Privacy Policy', terms: 'Terms of Service' },
    currency: 'MAD'
  },
  fr: {
    nav: { collections: 'COLLECTIONS', perfumes: 'PARFUMS', clothing: 'VÊTEMENTS', search: 'Rechercher...', admin: 'Panneau Admin', store: 'Boutique' },
    hero: { subtitle: 'NOUVELLE COLLECTION 2024', title: 'L\'Essence de l\'Élégance', cta: 'Acheter Maintenant' },
    store: { title: 'Sélection Organisée', description: 'Découvrez notre collection de fragrances artisanales et de vêtements sur mesure.', all: 'Tout', perfume: 'Parfum', clothing: 'Vêtement', addToBag: 'Ajouter au Panier', noProducts: 'Aucun produit trouvé', adjustSearch: 'Essayez d\'ajuster votre recherche ou vos filtres.' },
    product: { back: 'Retour à la collection', inStock: 'En stock', lowStock: 'Plus que {count}', outOfStock: 'Rupture de stock', notes: 'Notes olfactives', materials: 'Matières', material: 'Matière', color: 'Couleur', scentFamily: 'Famille olfactive', topNotes: 'Notes de tête', heartNotes: 'Notes de coeur', baseNotes: 'Notes de fond', volume: 'Volume', size: 'Taille', delivery: 'Livraison', defaultNote: 'Mélange signature', defaultMaterial: 'Finition premium', defaultColor: 'Couleur saisonnière', defaultScentFamily: 'Parfum signature', defaultVolume: '50 ml', defaultSize: 'Taille unique', defaultDelivery: 'Livraison en 2 à 4 jours ouvrables' },
    cart: { title: 'Panier', empty: 'Votre panier est vide', itemCount: '{count} articles dans votre panier', startShopping: 'Commencer vos achats', continueShopping: 'Continuer vos achats', clear: 'Vider le panier', each: 'chacun', stockLimit: 'Stock maximum atteint', subtotal: 'Sous-total', shipping: 'Livraison', shippingNote: 'Calculé à la caisse', total: 'Total', checkout: 'Passer à la caisse', hideCheckout: 'Masquer le paiement' },
    checkout: { title: 'Confirmation de commande', description: 'Vérifiez la commande, ajoutez les informations de livraison, puis envoyez-la au vendeur sur WhatsApp.', orderSummary: 'Résumé de commande', paymentInstructions: 'Instructions de paiement', whatsapp: 'Envoyer la commande sur WhatsApp', bank: 'Informations bancaires', bankName: 'Banque', accountHolder: 'Titulaire du compte', rib: 'RIB', iban: 'IBAN', note: 'Utilisez les informations bancaires ci-dessus pour les virements. Après le paiement, envoyez le reçu du virement par WhatsApp.', customerDetails: 'Informations client :', form: { title: 'Informations de livraison', name: 'Nom complet', phone: 'Numéro de téléphone', city: 'Ville', address: 'Adresse', notes: 'Notes de livraison (optionnel)', required: 'Le nom, le téléphone, la ville et l’adresse sont obligatoires avant l’envoi.' }, messageGreeting: 'Bonjour, je souhaite passer cette commande :', messageDelivery: 'Merci de confirmer la disponibilité et les informations de livraison.' },
    admin: { title: 'Gestion de l\'Inventaire', description: 'Gérez votre catalogue de produits, vos niveaux de stock et la valeur de l\'inventaire.', addBtn: 'Ajouter un Produit', search: 'Rechercher des produits...', lowStock: 'Stock bas', stats: { products: 'Produits', units: 'Unités en stock', value: 'Valeur du stock', lowStock: 'Stock bas' }, seller: { title: 'Paramètres vendeur', description: 'Mettez à jour le WhatsApp et les informations bancaires visibles au paiement.', whatsapp: 'WhatsApp', bankName: 'Nom de la banque', accountHolder: 'Titulaire du compte', rib: 'RIB', iban: 'IBAN', save: 'Enregistrer le vendeur' }, table: { product: 'Produit', category: 'Catégorie', price: 'Prix', stock: 'Stock', actions: 'Actions', units: 'unités' }, modal: { addTitle: 'Ajouter un Produit', editTitle: 'Modifier le Produit', name: 'Nom du Produit', desc: 'Description', price: 'Prix (MAD)', stock: 'Stock', category: 'Catégorie', image: 'URL de l\'image', preview: 'Aperçu de l’image', previewHelp: 'L’image du produit apparaîtra ici.', imageFallback: 'L’image ne charge pas, l’image de secours est affichée.', volume: 'Volume', scentFamily: 'Famille olfactive', topNotes: 'Notes de tête', heartNotes: 'Notes de coeur', baseNotes: 'Notes de fond', size: 'Taille', color: 'Couleur', material: 'Matière', delivery: 'Livraison', commaSeparated: 'Séparez les valeurs par des virgules', save: 'Enregistrer', create: 'Créer le Produit' }, deleteConfirm: 'Êtes-vous sûr de vouloir supprimer ce produit ?' },
    footer: { desc: 'Créer une élégance intemporelle à travers des parfums artisanaux et une mode sur mesure. Notre mission est d\'apporter luxe et qualité à votre quotidien.', shop: 'Boutique', support: 'Support', rights: '© 2024 Luxe & Loom Boutique. Tous droits réservés.', privacy: 'Politique de Confidentialité', terms: 'Conditions d\'Utilisation' },
    currency: 'MAD'
  },
  ar: {
    nav: { collections: 'المجموعات', perfumes: 'العطور', clothing: 'الملابس', search: 'بحث...', admin: 'لوحة التحكم', store: 'المتجر' },
    hero: { subtitle: 'مجموعة جديدة 2024', title: 'جوهر الأناقة', cta: 'تسوق الآن' },
    store: { title: 'مجموعة مختارة', description: 'اكتشف مجموعتنا المختارة من العطور الحرفية والملابس المصممة خصيصاً.', all: 'الكل', perfume: 'عطر', clothing: 'ملابس', addToBag: 'أضف إلى السلة', noProducts: 'لم يتم العثور على منتجات', adjustSearch: 'حاول تعديل البحث أو الفلاتر.' },
    product: { back: 'العودة إلى المجموعة', inStock: 'متوفر', lowStock: 'باقي {count} فقط', outOfStock: 'غير متوفر', notes: 'نوتات العطر', materials: 'المواد', material: 'الخامة', color: 'اللون', scentFamily: 'العائلة العطرية', topNotes: 'النوتات العليا', heartNotes: 'نوتات القلب', baseNotes: 'نوتات القاعدة', volume: 'الحجم', size: 'المقاس', delivery: 'التوصيل', defaultNote: 'تركيبة مميزة', defaultMaterial: 'تشطيب فاخر', defaultColor: 'لون موسمي', defaultScentFamily: 'عطر مميز', defaultVolume: '50 مل', defaultSize: 'مقاس واحد', defaultDelivery: 'التوصيل خلال 2 إلى 4 أيام عمل' },
    cart: { title: 'حقيبة التسوق', empty: 'حقيبتك فارغة', itemCount: '{count} منتجات في الحقيبة', startShopping: 'ابدأ التسوق', continueShopping: 'متابعة التسوق', clear: 'إفراغ الحقيبة', each: 'للوحدة', stockLimit: 'وصلت للحد المتوفر', subtotal: 'المجموع الفرعي', shipping: 'الشحن', shippingNote: 'يتم حسابه عند الدفع', total: 'الإجمالي', checkout: 'الدفع الآن', hideCheckout: 'إخفاء الدفع' },
    checkout: { title: 'تأكيد الطلب', description: 'راجع الطلب وأضف معلومات التوصيل ثم أرسله إلى البائع عبر واتساب.', orderSummary: 'ملخص الطلب', paymentInstructions: 'تعليمات الدفع', whatsapp: 'إرسال الطلب عبر واتساب', bank: 'المعلومات البنكية', bankName: 'البنك', accountHolder: 'صاحب الحساب', rib: 'RIB', iban: 'IBAN', note: 'استخدم المعلومات البنكية أعلاه للتحويل. بعد الدفع، أرسل وصل التحويل عبر واتساب.', customerDetails: 'معلومات الزبون:', form: { title: 'معلومات التوصيل', name: 'الاسم الكامل', phone: 'رقم الهاتف', city: 'المدينة', address: 'العنوان', notes: 'ملاحظات التوصيل (اختياري)', required: 'الاسم والهاتف والمدينة والعنوان مطلوبة قبل الإرسال.' }, messageGreeting: 'مرحباً، أريد طلب المنتجات التالية:', messageDelivery: 'يرجى تأكيد التوفر ومعلومات التوصيل.' },
    admin: { title: 'إدارة المخزون', description: 'إدارة كتالوج المنتجات ومستويات المخزون وقيمة البضائع.', addBtn: 'إضافة منتج جديد', search: 'ابحث عن المنتجات...', lowStock: 'مخزون منخفض', stats: { products: 'المنتجات', units: 'الوحدات في المخزون', value: 'قيمة المخزون', lowStock: 'مخزون منخفض' }, seller: { title: 'إعدادات البائع', description: 'حدّث رقم واتساب والمعلومات البنكية التي تظهر للزبون عند الدفع.', whatsapp: 'واتساب', bankName: 'اسم البنك', accountHolder: 'صاحب الحساب', rib: 'RIB', iban: 'IBAN', save: 'حفظ معلومات البائع' }, table: { product: 'المنتج', category: 'الفئة', price: 'السعر', stock: 'المخزون', actions: 'الإجراءات', units: 'وحدات' }, modal: { addTitle: 'إضافة منتج جديد', editTitle: 'تعديل المنتج', name: 'اسم المنتج', desc: 'الوصف', price: 'السعر (د.م.)', stock: 'المخزون', category: 'الفئة', image: 'رابط الصورة', preview: 'معاينة الصورة', previewHelp: 'ستظهر صورة المنتج هنا.', imageFallback: 'تعذر تحميل الصورة، لذلك تظهر الصورة البديلة.', volume: 'الحجم', scentFamily: 'العائلة العطرية', topNotes: 'النوتات العليا', heartNotes: 'نوتات القلب', baseNotes: 'نوتات القاعدة', size: 'المقاس', color: 'اللون', material: 'الخامة', delivery: 'التوصيل', commaSeparated: 'افصل القيم بفواصل', save: 'حفظ التغييرات', create: 'إنشاء المنتج' }, deleteConfirm: 'هل أنت متأكد أنك تريد حذف هذا المنتج؟' },
    footer: { desc: 'صياغة أناقة خالدة من خلال العطور الحرفية والأزياء المصممة خصيصاً. مهمتنا هي تقديم الفخامة والجودة لحياتك اليومية.', shop: 'تسوق', support: 'الدعم', rights: '© 2024 بوتيك Luxe & Loom. جميع الحقوق محفوظة.', privacy: 'سياسة الخصوصية', terms: 'شروط الخدمة' },
    currency: 'د.م.'
  }
};
